import Head from 'next/head'
import Avatar from '../components/Avatar'
import { MicrophoneIcon, ViewGridIcon} from "@heroicons/react/solid"
import { SearchIcon } from '@heroicons/react/outline'
import Image from 'next/dist/client/image'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className='flex flex-col  justify-center h-screen'>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='flex w-full p-5 justify-between text-sm text-gray-700'>
        {/* left */}
        <div className='flex space-x-4 items-center '>
          <p className='link'>About</p>
          <p className='link'>Store</p>
        </div>

        {/* right */}
        <div className='flex space-x-4 items-center'>
          <p className='link'>Gmail</p>
          <p className='link'>Image</p>

          {/* Icon */}
          <ViewGridIcon className='h-10 w-10 p-2 rounded-full hover:bg-gray-400 cursor-pointer' />
          {/* Avatar */}
          <Avatar url="https://thispersondoesnotexist.com/image"/>

        </div>
      </header>

        {/* body */}
        <form className='flex flex-col items-center mt-44 flex-grow'>
          <Image  width={300} height={100} src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png" />
          <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg rounded-full border border-gray-200 px-5 py-3 items-center sm:max-w-xl'>
            <SearchIcon className='h-5 mr-3 text-gray-500'/>
            <input className='flex-grow focus:outline-none' type="text" placeholder="Search" />
            <MicrophoneIcon className='h-5 '/>
          </div>
          <div className='flex flex-col w-1/2 space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4'>
            <button className='btn' >Google搜索</button>
            <button className='btn' >手气不错</button>
          </div>
        </form>

        {/* footer */}
        <Footer />
    </div>
  )
}
